name: Build and Push Docker Image

on: push



jobs:

    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image           
          run: |
            cd messaging_app

            echo "MYSQL_DATABASE=ci_message_app" >> messaging_app/.env
            echo "MYSQL_USER=ci_user" >> messaging_app/.env
            echo "MYSQL_PASSWORD=ci_password" >> messaging_app/.env
            echo "MYSQL_HOST=db" >> messaging_app/.env
            echo "MYSQL_ROOT_PASSWORD=root_pass" >> messaging_app/.env            

            docker compose build --no-cache --force-rm 

        
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - uses: actions/checkout@v2
        - name: Test the Docker image
          run: |
            cd messaging_app
            docker compose up -d


    push_to_registry:
        name: Push Docker image to Docker Hub
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Setup Docker buildX
              uses: docker/setup-buildx-action@v2

            - name: Login to docker
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PAT }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: docker.io/${{ secrets.DOCKER_USERNAME }}/messaging-app

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: ./messaging_app    
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

            

